// Code generated by goagen v1.1.0-dirty, command line:
// $ goagen
// --design=github.com/alligrader/gradebook-api/designs
// --out=$(GOPATH)/src/github.com/alligrader/gradebook-api/src
// --version=v1.1.0-dirty
//
// API "GradebookAPI": Application Resource Href Factories
//
// The content of this file is auto-generated, DO NOT MODIFY

package app

import (
	"fmt"
	"strings"
)

// BugProfileHref returns the resource href.
func BugProfileHref(profileID interface{}) string {
	paramprofileID := strings.TrimLeftFunc(fmt.Sprintf("%v", profileID), func(r rune) bool { return r == '/' })
	return fmt.Sprintf("/api/bug-profile/%v", paramprofileID)
}
