// Code generated by goagen v1.1.0-dirty, command line:
// $ goagen
// --design=github.com/alligrader/gradebook-api/designs
// --out=$(GOPATH)/src/github.com/alligrader/gradebook-api/src
// --version=v1.1.0-dirty
//
// API "GradebookAPI": Application User Types
//
// The content of this file is auto-generated, DO NOT MODIFY

package app

import "github.com/goadesign/goa"

// Description of which Checkstyle lints are checked.
type checkstyle struct {
	// The Check validate abbreviations(consecutive capital letters) length in identifier name, it also allow in enforce camel case naming.
	AbbreviationAsWordInName *bool `form:"AbbreviationAsWordInName,omitempty" json:"AbbreviationAsWordInName,omitempty" xml:"AbbreviationAsWordInName,omitempty"`
	// Ensures that the names of abstract classes conforming to some regular expression.
	AbstractClassName *bool `form:"AbstractClassName,omitempty" json:"AbstractClassName,omitempty" xml:"AbstractClassName,omitempty"`
	// Check location of annotation on language elements.
	AnnotationLocation *bool `form:"AnnotationLocation,omitempty" json:"AnnotationLocation,omitempty" xml:"AnnotationLocation,omitempty"`
	// This check controls the style with the usage of annotations.
	AnnotationUseStyle *bool `form:"AnnotationUseStyle,omitempty" json:"AnnotationUseStyle,omitempty" xml:"AnnotationUseStyle,omitempty"`
	// Checks for long anonymous inner classes.
	AnonInnerLength *bool `form:"AnonInnerLength,omitempty" json:"AnonInnerLength,omitempty" xml:"AnonInnerLength,omitempty"`
	// Checks if array initialization contains optional trailing comma.
	ArrayTrailingComma *bool `form:"ArrayTrailingComma,omitempty" json:"ArrayTrailingComma,omitempty" xml:"ArrayTrailingComma,omitempty"`
	// Checks the style of array type definitions.
	ArrayTypeStyle *bool `form:"ArrayTypeStyle,omitempty" json:"ArrayTypeStyle,omitempty" xml:"ArrayTypeStyle,omitempty"`
	// Checks the order of at-clauses.
	AtclauseOrder *bool `form:"AtclauseOrder,omitempty" json:"AtclauseOrder,omitempty" xml:"AtclauseOrder,omitempty"`
	// Restrict using Unicode escapes.
	AvoidEscapedUnicodeCharacters *bool `form:"AvoidEscapedUnicodeCharacters,omitempty" json:"AvoidEscapedUnicodeCharacters,omitempty" xml:"AvoidEscapedUnicodeCharacters,omitempty"`
	// Detects inline conditionals.
	AvoidInlineConditionals *bool `form:"AvoidInlineConditionals,omitempty" json:"AvoidInlineConditionals,omitempty" xml:"AvoidInlineConditionals,omitempty"`
	// Finds nested blocks.
	AvoidNestedBlocks *bool `form:"AvoidNestedBlocks,omitempty" json:"AvoidNestedBlocks,omitempty" xml:"AvoidNestedBlocks,omitempty"`
	// Check that finds import statements that use the * notation.
	AvoidStarImport *bool `form:"AvoidStarImport,omitempty" json:"AvoidStarImport,omitempty" xml:"AvoidStarImport,omitempty"`
	// Check that finds static imports.
	AvoidStaticImport *bool `form:"AvoidStaticImport,omitempty" json:"AvoidStaticImport,omitempty" xml:"AvoidStaticImport,omitempty"`
	// Restricts nested boolean operators (&&, ||, &, | and ^) to a specified depth (default = 3).
	BooleanExpressionComplexity *bool `form:"BooleanExpressionComplexity,omitempty" json:"BooleanExpressionComplexity,omitempty" xml:"BooleanExpressionComplexity,omitempty"`
	// Checks that catch parameter names conform to a format specified by the format property.
	CatchParameterName *bool `form:"CatchParameterName,omitempty" json:"CatchParameterName,omitempty" xml:"CatchParameterName,omitempty"`
	// This metric measures the number of instantiations of other classes within the given class.
	ClassDataAbstractionCoupling *bool `form:"ClassDataAbstractionCoupling,omitempty" json:"ClassDataAbstractionCoupling,omitempty" xml:"ClassDataAbstractionCoupling,omitempty"`
	// The number of other classes a given class relies on.
	ClassFanOutComplexity *bool `form:"ClassFanOutComplexity,omitempty" json:"ClassFanOutComplexity,omitempty" xml:"ClassFanOutComplexity,omitempty"`
	// Checks that class type parameter names conform to a format specified by the format property.
	ClassTypeParameterName *bool `form:"ClassTypeParameterName,omitempty" json:"ClassTypeParameterName,omitempty" xml:"ClassTypeParameterName,omitempty"`
	// Controls the indentation between comments and surrounding code.
	CommentsIndentation *bool `form:"CommentsIndentation,omitempty" json:"CommentsIndentation,omitempty" xml:"CommentsIndentation,omitempty"`
	// Checks that constant names conform to a format specified by the format property.
	ConstantName *bool `form:"ConstantName,omitempty" json:"ConstantName,omitempty" xml:"ConstantName,omitempty"`
	// Checks that if a class defines a covariant method equals, then it defines method equals(java.lang.Object).
	CovariantEquals *bool `form:"CovariantEquals,omitempty" json:"CovariantEquals,omitempty" xml:"CovariantEquals,omitempty"`
	// Checks that the groups of import declarations appear in the order specified by the user.
	CustomImportOrder *bool `form:"CustomImportOrder,omitempty" json:"CustomImportOrder,omitempty" xml:"CustomImportOrder,omitempty"`
	// Checks cyclomatic complexity against a specified limit.
	CyclomaticComplexity *bool `form:"CyclomaticComplexity,omitempty" json:"CyclomaticComplexity,omitempty" xml:"CyclomaticComplexity,omitempty"`
	// Checks that the parts of a class or interface declaration appear in the order suggested by the Code Conventions for the Java Programming Language.
	DeclarationOrder *bool `form:"DeclarationOrder,omitempty" json:"DeclarationOrder,omitempty" xml:"DeclarationOrder,omitempty"`
	// Check that the default is after all the cases in a switch statement.
	DefaultComesLast *bool `form:"DefaultComesLast,omitempty" json:"DefaultComesLast,omitempty" xml:"DefaultComesLast,omitempty"`
	// Checks for restricted tokens beneath other tokens.
	DescendantToken *bool `form:"DescendantToken,omitempty" json:"DescendantToken,omitempty" xml:"DescendantToken,omitempty"`
	// Checks that classes are designed for inheritance.
	DesignForExtension *bool `form:"DesignForExtension,omitempty" json:"DesignForExtension,omitempty" xml:"DesignForExtension,omitempty"`
	// Checks for empty blocks.
	EmptyBlock *bool `form:"EmptyBlock,omitempty" json:"EmptyBlock,omitempty" xml:"EmptyBlock,omitempty"`
	// Checks for empty catch blocks with few options to skip violation.
	EmptyCatchBlock *bool `form:"EmptyCatchBlock,omitempty" json:"EmptyCatchBlock,omitempty" xml:"EmptyCatchBlock,omitempty"`
	// Checks the padding of an empty for initializer; that is whether a space is required at an empty for initializer, or such spaces are forbidden.
	EmptyForInitializerPad *bool `form:"EmptyForInitializerPad,omitempty" json:"EmptyForInitializerPad,omitempty" xml:"EmptyForInitializerPad,omitempty"`
	// Checks the padding of an empty for iterator; that is whether a space is required at an empty for iterator, or such spaces are forbidden.
	EmptyForIteratorPad *bool `form:"EmptyForIteratorPad,omitempty" json:"EmptyForIteratorPad,omitempty" xml:"EmptyForIteratorPad,omitempty"`
	// Checks for blank line separators.
	EmptyLineSeparator *bool `form:"EmptyLineSeparator,omitempty" json:"EmptyLineSeparator,omitempty" xml:"EmptyLineSeparator,omitempty"`
	// Detects empty statements (standalone ';').
	EmptyStatement *bool `form:"EmptyStatement,omitempty" json:"EmptyStatement,omitempty" xml:"EmptyStatement,omitempty"`
	// Checks that any combination of String literals is on the left side of an equals() comparison.
	EqualsAvoidNull *bool `form:"EqualsAvoidNull,omitempty" json:"EqualsAvoidNull,omitempty" xml:"EqualsAvoidNull,omitempty"`
	// Checks that classes that override equals() also override hashCode().
	EqualsHashCode *bool `form:"EqualsHashCode,omitempty" json:"EqualsHashCode,omitempty" xml:"EqualsHashCode,omitempty"`
	// Restricts the number of executable statements to a specified limit (default = 30).
	ExecutableStatementCount *bool `form:"ExecutableStatementCount,omitempty" json:"ExecutableStatementCount,omitempty" xml:"ExecutableStatementCount,omitempty"`
	// Checks if any class or object member explicitly initialized to default for its type value (null for object references, zero for numeric types and char and false for boolean.
	ExplicitInitialization *bool `form:"ExplicitInitialization,omitempty" json:"ExplicitInitialization,omitempty" xml:"ExplicitInitialization,omitempty"`
	// Checks for fall through in switch statements Finds locations where a case contains Java code - but lacks a break, return, throw or continue statement.
	FallThrough *bool `form:"FallThrough,omitempty" json:"FallThrough,omitempty" xml:"FallThrough,omitempty"`
	// Checks for long source files.
	FileLength *bool `form:"FileLength,omitempty" json:"FileLength,omitempty" xml:"FileLength,omitempty"`
	// Checks to see if a file contains a tab character.
	FileTabCharacter *bool `form:"FileTabCharacter,omitempty" json:"FileTabCharacter,omitempty" xml:"FileTabCharacter,omitempty"`
	// Checks that class which has only private constructors is declared as final.
	FinalClass *bool `form:"FinalClass,omitempty" json:"FinalClass,omitempty" xml:"FinalClass,omitempty"`
	// Ensures that local variables that never get their values changed, must be declared final.
	FinalLocalVariable *bool `form:"FinalLocalVariable,omitempty" json:"FinalLocalVariable,omitempty" xml:"FinalLocalVariable,omitempty"`
	// Check that method/constructor/catch/foreach parameters are final.
	FinalParameters *bool `form:"FinalParameters,omitempty" json:"FinalParameters,omitempty" xml:"FinalParameters,omitempty"`
	// Checks that the whitespace around the Generic tokens < and > are correct to the typical convention.
	GenericWhitespace *bool `form:"GenericWhitespace,omitempty" json:"GenericWhitespace,omitempty" xml:"GenericWhitespace,omitempty"`
	// Checks the header of the source against a fixed header file.
	Header *bool `form:"Header,omitempty" json:"Header,omitempty" xml:"Header,omitempty"`
	// Checks that a local variable or a parameter does not shadow a field that is defined in the same class.
	HiddenField *bool `form:"HiddenField,omitempty" json:"HiddenField,omitempty" xml:"HiddenField,omitempty"`
	// Make sure that utility classes (classes that contain only static methods) do not have a public constructor.
	HideUtilityClassConstructor *bool `form:"HideUtilityClassConstructor,omitempty" json:"HideUtilityClassConstructor,omitempty" xml:"HideUtilityClassConstructor,omitempty"`
	// Catching java.lang.Exception, java.lang.Error or java.lang.RuntimeException is almost never acceptable.
	IllegalCatch *bool `form:"IllegalCatch,omitempty" json:"IllegalCatch,omitempty" xml:"IllegalCatch,omitempty"`
	// Checks for imports from a set of illegal packages.
	IllegalImport *bool `form:"IllegalImport,omitempty" json:"IllegalImport,omitempty" xml:"IllegalImport,omitempty"`
	// Checks for illegal instantiations where a factory method is preferred.
	IllegalInstantiation *bool `form:"IllegalInstantiation,omitempty" json:"IllegalInstantiation,omitempty" xml:"IllegalInstantiation,omitempty"`
	// Throwing java.lang.Error or java.lang.RuntimeException is almost never acceptable.
	IllegalThrows *bool `form:"IllegalThrows,omitempty" json:"IllegalThrows,omitempty" xml:"IllegalThrows,omitempty"`
	// Checks for illegal tokens.
	IllegalToken *bool `form:"IllegalToken,omitempty" json:"IllegalToken,omitempty" xml:"IllegalToken,omitempty"`
	// Checks for illegal token text.
	IllegalTokenText *bool `form:"IllegalTokenText,omitempty" json:"IllegalTokenText,omitempty" xml:"IllegalTokenText,omitempty"`
	// Checks that particular class are never used as types in variable declarations, return values or parameters.
	IllegalType *bool `form:"IllegalType,omitempty" json:"IllegalType,omitempty" xml:"IllegalType,omitempty"`
	// Check that controls what packages can be imported in each package.
	ImportControl *bool `form:"ImportControl,omitempty" json:"ImportControl,omitempty" xml:"ImportControl,omitempty"`
	// Ensures that groups of imports come in a specific order.
	ImportOrder *bool `form:"ImportOrder,omitempty" json:"ImportOrder,omitempty" xml:"ImportOrder,omitempty"`
	// Checks correct indentation of Java Code.
	Indentation *bool `form:"Indentation,omitempty" json:"Indentation,omitempty" xml:"Indentation,omitempty"`
	// Checks for assignments in subexpressions, such as in String s = Integer.toString(i = 2);.
	InnerAssignment *bool `form:"InnerAssignment,omitempty" json:"InnerAssignment,omitempty" xml:"InnerAssignment,omitempty"`
	// Check nested (internal) classes/interfaces are declared at the bottom of the class after all method and field declarations.
	InnerTypeLast *bool `form:"InnerTypeLast,omitempty" json:"InnerTypeLast,omitempty" xml:"InnerTypeLast,omitempty"`
	// Implements Bloch, Effective Java, Item 17 - Use Interfaces only to define types.
	InterfaceIsType *bool `form:"InterfaceIsType,omitempty" json:"InterfaceIsType,omitempty" xml:"InterfaceIsType,omitempty"`
	// Checks that interface type parameter names conform to a format specified by the format property.
	InterfaceTypeParameterName *bool `form:"InterfaceTypeParameterName,omitempty" json:"InterfaceTypeParameterName,omitempty" xml:"InterfaceTypeParameterName,omitempty"`
	// This check calculates the Non Commenting Source Statements (NCSS) metric for Java source files and methods.
	JavaNCSS *bool `form:"JavaNCSS,omitempty" json:"JavaNCSS,omitempty" xml:"JavaNCSS,omitempty"`
	// Checks the Javadoc of a method or constructor.
	JavadocMethod *bool `form:"JavadocMethod,omitempty" json:"JavadocMethod,omitempty" xml:"JavadocMethod,omitempty"`
	// Checks that all packages have a package documentation.
	JavadocPackage *bool `form:"JavadocPackage,omitempty" json:"JavadocPackage,omitempty" xml:"JavadocPackage,omitempty"`
	// Checks Javadoc paragraphs.
	JavadocParagraph *bool `form:"JavadocParagraph,omitempty" json:"JavadocParagraph,omitempty" xml:"JavadocParagraph,omitempty"`
	// Custom Checkstyle Check to validate Javadoc.
	JavadocStyle *bool `form:"JavadocStyle,omitempty" json:"JavadocStyle,omitempty" xml:"JavadocStyle,omitempty"`
	// Checks the indentation of the continuation lines in at-clauses.
	JavadocTagContinuationIndentation *bool `form:"JavadocTagContinuationIndentation,omitempty" json:"JavadocTagContinuationIndentation,omitempty" xml:"JavadocTagContinuationIndentation,omitempty"`
	// Checks the Javadoc of a type.
	JavadocType *bool `form:"JavadocType,omitempty" json:"JavadocType,omitempty" xml:"JavadocType,omitempty"`
	// Checks that a variable has Javadoc comment.
	JavadocVariable *bool `form:"JavadocVariable,omitempty" json:"JavadocVariable,omitempty" xml:"JavadocVariable,omitempty"`
	// Checks the placement of left curly braces on types, methods and other blocks:
	LeftCurly *bool `form:"LeftCurly,omitempty" json:"LeftCurly,omitempty" xml:"LeftCurly,omitempty"`
	// Checks for long lines.
	LineLength *bool `form:"LineLength,omitempty" json:"LineLength,omitempty" xml:"LineLength,omitempty"`
	// Checks that local final variable names conform to a format specified by the format property.
	LocalFinalVariableName *bool `form:"LocalFinalVariableName,omitempty" json:"LocalFinalVariableName,omitempty" xml:"LocalFinalVariableName,omitempty"`
	// Checks that local, non-final variable names conform to a format specified by the format property.
	LocalVariableName *bool `form:"LocalVariableName,omitempty" json:"LocalVariableName,omitempty" xml:"LocalVariableName,omitempty"`
	// Checks for magic numbers.
	MagicNumber *bool `form:"MagicNumber,omitempty" json:"MagicNumber,omitempty" xml:"MagicNumber,omitempty"`
	// Checks that instance variable names conform to a format specified by the format property.
	MemberName *bool `form:"MemberName,omitempty" json:"MemberName,omitempty" xml:"MemberName,omitempty"`
	// Checks the number of methods declared in each type.
	MethodCount *bool `form:"MethodCount,omitempty" json:"MethodCount,omitempty" xml:"MethodCount,omitempty"`
	// Checks for long methods.
	MethodLength *bool `form:"MethodLength,omitempty" json:"MethodLength,omitempty" xml:"MethodLength,omitempty"`
	// Checks that method names conform to a format specified by the format property.
	MethodName *bool `form:"MethodName,omitempty" json:"MethodName,omitempty" xml:"MethodName,omitempty"`
	// Checks the padding between the identifier of a method definition, constructor definition, method call, or constructor invocation; and the left parenthesis of the parameter list.
	MethodParamPad *bool `form:"MethodParamPad,omitempty" json:"MethodParamPad,omitempty" xml:"MethodParamPad,omitempty"`
	// Checks that class type parameter names conform to a format specified by the format property.
	MethodTypeParameterName *bool `form:"MethodTypeParameterName,omitempty" json:"MethodTypeParameterName,omitempty" xml:"MethodTypeParameterName,omitempty"`
	// Checks that classes (except abstract one) define a ctor and don't rely on the default one.
	MissingCtor *bool `form:"MissingCtor,omitempty" json:"MissingCtor,omitempty" xml:"MissingCtor,omitempty"`
	// This class is used to verify that both the java.lang.Deprecated annotation is present and the @deprecated Javadoc tag is present when either is present.
	MissingDeprecated *bool `form:"MissingDeprecated,omitempty" json:"MissingDeprecated,omitempty" xml:"MissingDeprecated,omitempty"`
	// This class is used to verify that the java.lang.Override annotation is present when the {@inheritDoc} javadoc tag is present.
	MissingOverride *bool `form:"MissingOverride,omitempty" json:"MissingOverride,omitempty" xml:"MissingOverride,omitempty"`
	// Checks that switch statement has 'default' clause.
	MissingSwitchDefault *bool `form:"MissingSwitchDefault,omitempty" json:"MissingSwitchDefault,omitempty" xml:"MissingSwitchDefault,omitempty"`
	// Check for ensuring that for loop control variables are not modified inside the for block.
	ModifiedControlVariable *bool `form:"ModifiedControlVariable,omitempty" json:"ModifiedControlVariable,omitempty" xml:"ModifiedControlVariable,omitempty"`
	// Checks that the order of modifiers conforms to the suggestions in the Java Language specification, sections 8.1.1, 8.3.1 and 8.4.3.
	ModifierOrder *bool `form:"ModifierOrder,omitempty" json:"ModifierOrder,omitempty" xml:"ModifierOrder,omitempty"`
	// Checks for multiple occurrences of the same string literal within a single file.
	MultipleStringLiterals *bool `form:"MultipleStringLiterals,omitempty" json:"MultipleStringLiterals,omitempty" xml:"MultipleStringLiterals,omitempty"`
	// Checks that each variable declaration is in its own statement and on its own line.
	MultipleVariableDeclarations *bool `form:"MultipleVariableDeclarations,omitempty" json:"MultipleVariableDeclarations,omitempty" xml:"MultipleVariableDeclarations,omitempty"`
	// Ensures that exceptions (defined as any class name conforming to some regular expression) are immutable.
	MutableException *bool `form:"MutableException,omitempty" json:"MutableException,omitempty" xml:"MutableException,omitempty"`
	// Checks the npath complexity against a specified limit (default = 200).
	NPathComplexity *bool `form:"NPathComplexity,omitempty" json:"NPathComplexity,omitempty" xml:"NPathComplexity,omitempty"`
	// Checks for braces around code blocks.
	NeedBraces *bool `form:"NeedBraces,omitempty" json:"NeedBraces,omitempty" xml:"NeedBraces,omitempty"`
	// Restricts nested for blocks to a specified depth (default = 1).
	NestedForDepth *bool `form:"NestedForDepth,omitempty" json:"NestedForDepth,omitempty" xml:"NestedForDepth,omitempty"`
	// Restricts nested if-else blocks to a specified depth (default = 1).
	NestedIfDepth *bool `form:"NestedIfDepth,omitempty" json:"NestedIfDepth,omitempty" xml:"NestedIfDepth,omitempty"`
	// Restricts nested try-catch-finally blocks to a specified depth (default = 1).
	NestedTryDepth *bool `form:"NestedTryDepth,omitempty" json:"NestedTryDepth,omitempty" xml:"NestedTryDepth,omitempty"`
	// Checks that there is a newline at the end of each file.
	NewlineAtEndOfFile *bool `form:"NewlineAtEndOfFile,omitempty" json:"NewlineAtEndOfFile,omitempty" xml:"NewlineAtEndOfFile,omitempty"`
	// Checks that the clone method is not overridden from the Object class.
	NoClone *bool `form:"NoClone,omitempty" json:"NoClone,omitempty" xml:"NoClone,omitempty"`
	// Checks that no method having zero parameters is defined using the name finalize.
	NoFinalizer *bool `form:"NoFinalizer,omitempty" json:"NoFinalizer,omitempty" xml:"NoFinalizer,omitempty"`
	// Checks that chosen statements are not line-wrapped.
	NoLineWrap *bool `form:"NoLineWrap,omitempty" json:"NoLineWrap,omitempty" xml:"NoLineWrap,omitempty"`
	// Checks that there is no whitespace after a token.
	NoWhitespaceAfter *bool `form:"NoWhitespaceAfter,omitempty" json:"NoWhitespaceAfter,omitempty" xml:"NoWhitespaceAfter,omitempty"`
	// Checks that there is no whitespace before a token.
	NoWhitespaceBefore *bool `form:"NoWhitespaceBefore,omitempty" json:"NoWhitespaceBefore,omitempty" xml:"NoWhitespaceBefore,omitempty"`
	// Checks that the at-clause tag is followed by description .
	NonEmptyAtclauseDescription *bool `form:"NonEmptyAtclauseDescription,omitempty" json:"NonEmptyAtclauseDescription,omitempty" xml:"NonEmptyAtclauseDescription,omitempty"`
	// Checks that there is only one statement per line.
	OneStatementPerLine *bool `form:"OneStatementPerLine,omitempty" json:"OneStatementPerLine,omitempty" xml:"OneStatementPerLine,omitempty"`
	// Checks that each top-level class, interfaces or enum resides in a source file of its own.
	OneTopLevelClass *bool `form:"OneTopLevelClass,omitempty" json:"OneTopLevelClass,omitempty" xml:"OneTopLevelClass,omitempty"`
	// Checks line wrapping for operators.
	OperatorWrap *bool `form:"OperatorWrap,omitempty" json:"OperatorWrap,omitempty" xml:"OperatorWrap,omitempty"`
	// Checks that the outer type name and the file name match.
	OuterTypeFilename *bool `form:"OuterTypeFilename,omitempty" json:"OuterTypeFilename,omitempty" xml:"OuterTypeFilename,omitempty"`
	// Checks for the number of defined types at the 'outer' level.
	OuterTypeNumber *bool `form:"OuterTypeNumber,omitempty" json:"OuterTypeNumber,omitempty" xml:"OuterTypeNumber,omitempty"`
	// Checks that overload methods are grouped together.
	OverloadMethodsDeclarationOrder *bool `form:"OverloadMethodsDeclarationOrder,omitempty" json:"OverloadMethodsDeclarationOrder,omitempty" xml:"OverloadMethodsDeclarationOrder,omitempty"`
	// This check makes sure that all package annotations are in the package-info.java file.
	PackageAnnotation *bool `form:"PackageAnnotation,omitempty" json:"PackageAnnotation,omitempty" xml:"PackageAnnotation,omitempty"`
	// Ensures there is a package declaration and (optionally) in the correct directory.
	PackageDeclaration *bool `form:"PackageDeclaration,omitempty" json:"PackageDeclaration,omitempty" xml:"PackageDeclaration,omitempty"`
	// Checks that package names conform to a format specified by the format property.
	PackageName *bool `form:"PackageName,omitempty" json:"PackageName,omitempty" xml:"PackageName,omitempty"`
	// Disallow assignment of parameters.
	ParameterAssignment *bool `form:"ParameterAssignment,omitempty" json:"ParameterAssignment,omitempty" xml:"ParameterAssignment,omitempty"`
	// Checks that parameter names conform to a format specified by the format property.
	ParameterName *bool `form:"ParameterName,omitempty" json:"ParameterName,omitempty" xml:"ParameterName,omitempty"`
	// Checks the number of parameters that a method or constructor has.
	ParameterNumber *bool `form:"ParameterNumber,omitempty" json:"ParameterNumber,omitempty" xml:"ParameterNumber,omitempty"`
	// Checks the padding of parentheses; that is whether a space is required after a left parenthesis and before a right parenthesis, or such spaces are forbidden, with the exception that it does not check for padding of the right parenthesis at an empty for iterator.
	ParenPad *bool `form:"ParenPad,omitempty" json:"ParenPad,omitempty" xml:"ParenPad,omitempty"`
	// Checks for imports that are redundant.
	RedundantImport *bool `form:"RedundantImport,omitempty" json:"RedundantImport,omitempty" xml:"RedundantImport,omitempty"`
	// Checks for redundant modifiers in interface and annotation definitions, final modifier on methods of final classes, inner interface declarations that are declared as static, non public class constructors and enum constructors, nested enum definitions that are declared as static.
	RedundantModifier *bool `form:"RedundantModifier,omitempty" json:"RedundantModifier,omitempty" xml:"RedundantModifier,omitempty"`
	// A check that makes sure that a specified pattern exists (or not) in the file.
	Regexp *bool `form:"Regexp,omitempty" json:"Regexp,omitempty" xml:"Regexp,omitempty"`
	// Checks the header of the source against a header file that contains a
	RegexpHeader *bool `form:"RegexpHeader,omitempty" json:"RegexpHeader,omitempty" xml:"RegexpHeader,omitempty"`
	// Implementation of a check that looks that matches across multiple lines in any file type.
	RegexpMultiline *bool `form:"RegexpMultiline,omitempty" json:"RegexpMultiline,omitempty" xml:"RegexpMultiline,omitempty"`
	// Implementation of a check that matches based on file and/or folder path.
	RegexpOnFilename *bool `form:"RegexpOnFilename,omitempty" json:"RegexpOnFilename,omitempty" xml:"RegexpOnFilename,omitempty"`
	// Implementation of a check that looks for a single line in any file type.
	RegexpSingleline *bool `form:"RegexpSingleline,omitempty" json:"RegexpSingleline,omitempty" xml:"RegexpSingleline,omitempty"`
	// Implementation of a check that looks for a single line in Java files.
	RegexpSinglelineJava *bool `form:"RegexpSinglelineJava,omitempty" json:"RegexpSinglelineJava,omitempty" xml:"RegexpSinglelineJava,omitempty"`
	// Checks that code doesn't rely on the 'this' default.
	RequireThis *bool `form:"RequireThis,omitempty" json:"RequireThis,omitempty" xml:"RequireThis,omitempty"`
	// Restricts return statements to a specified count (default = 2).
	ReturnCount *bool `form:"ReturnCount,omitempty" json:"ReturnCount,omitempty" xml:"ReturnCount,omitempty"`
	// Checks the placement of right curly braces.
	RightCurly *bool `form:"RightCurly,omitempty" json:"RightCurly,omitempty" xml:"RightCurly,omitempty"`
	// Checks line wrapping with separators.
	SeparatorWrap *bool `form:"SeparatorWrap,omitempty" json:"SeparatorWrap,omitempty" xml:"SeparatorWrap,omitempty"`
	// Checks for overly complicated boolean expressions.
	SimplifyBooleanExpression *bool `form:"SimplifyBooleanExpression,omitempty" json:"SimplifyBooleanExpression,omitempty" xml:"SimplifyBooleanExpression,omitempty"`
	// Checks for overly complicated boolean return statements.
	SimplifyBooleanReturn *bool `form:"SimplifyBooleanReturn,omitempty" json:"SimplifyBooleanReturn,omitempty" xml:"SimplifyBooleanReturn,omitempty"`
	// Checks that a JavaDoc block which can fit on a single line and doesn't contain at-clauses
	SingleLineJavadoc *bool `form:"SingleLineJavadoc,omitempty" json:"SingleLineJavadoc,omitempty" xml:"SingleLineJavadoc,omitempty"`
	// Checks that non-whitespace characters are separated by no more than one whitespace.
	SingleSpaceSeparator *bool `form:"SingleSpaceSeparator,omitempty" json:"SingleSpaceSeparator,omitempty" xml:"SingleSpaceSeparator,omitempty"`
	// Checks that static, non-final variable names conform to a format specified by the format property.
	StaticVariableName *bool `form:"StaticVariableName,omitempty" json:"StaticVariableName,omitempty" xml:"StaticVariableName,omitempty"`
	// Checks that string literals are not used with == or !=.
	StringLiteralEquality *bool `form:"StringLiteralEquality,omitempty" json:"StringLiteralEquality,omitempty" xml:"StringLiteralEquality,omitempty"`
	// Checks that Javadoc summary sentence does not contain phrases that are not recommended to use.
	SummaryJavadoc *bool `form:"SummaryJavadoc,omitempty" json:"SummaryJavadoc,omitempty" xml:"SummaryJavadoc,omitempty"`
	// Checks that an overriding clone() method invokes super.clone().
	SuperClone *bool `form:"SuperClone,omitempty" json:"SuperClone,omitempty" xml:"SuperClone,omitempty"`
	// Checks that an overriding finalize() method invokes super.finalize().
	SuperFinalize *bool `form:"SuperFinalize,omitempty" json:"SuperFinalize,omitempty" xml:"SuperFinalize,omitempty"`
	// This check allows you to specify what warnings that
	SuppressWarnings *bool `form:"SuppressWarnings,omitempty" json:"SuppressWarnings,omitempty" xml:"SuppressWarnings,omitempty"`
	// This check allows for finding code that should not be reported by Checkstyle
	SuppressWarningsHolder *bool `form:"SuppressWarningsHolder,omitempty" json:"SuppressWarningsHolder,omitempty" xml:"SuppressWarningsHolder,omitempty"`
	// Restricts throws statements to a specified count (default = 4).
	ThrowsCount *bool `form:"ThrowsCount,omitempty" json:"ThrowsCount,omitempty" xml:"ThrowsCount,omitempty"`
	// A check for TODO comments.
	TodoComment *bool `form:"TodoComment,omitempty" json:"TodoComment,omitempty" xml:"TodoComment,omitempty"`
	// The check to ensure that requires that comments be the only thing on a line.
	TrailingComment *bool `form:"TrailingComment,omitempty" json:"TrailingComment,omitempty" xml:"TrailingComment,omitempty"`
	// The TranslationCheck class helps to ensure the correct translation of code by checking property files for consistency regarding their keys.
	Translation *bool `form:"Translation,omitempty" json:"Translation,omitempty" xml:"Translation,omitempty"`
	// Checks that type names conform to a format specified by the format property.
	TypeName *bool `form:"TypeName,omitempty" json:"TypeName,omitempty" xml:"TypeName,omitempty"`
	// Checks the padding of parentheses for typecasts.
	TypecastParenPad *bool `form:"TypecastParenPad,omitempty" json:"TypecastParenPad,omitempty" xml:"TypecastParenPad,omitempty"`
	// Detects uncommented main methods.
	UncommentedMain *bool `form:"UncommentedMain,omitempty" json:"UncommentedMain,omitempty" xml:"UncommentedMain,omitempty"`
	// Detects duplicated keys in properties files.
	UniqueProperties *bool `form:"UniqueProperties,omitempty" json:"UniqueProperties,omitempty" xml:"UniqueProperties,omitempty"`
	// Checks if unnecessary parentheses are used in a statement or expression.
	UnnecessaryParentheses *bool `form:"UnnecessaryParentheses,omitempty" json:"UnnecessaryParentheses,omitempty" xml:"UnnecessaryParentheses,omitempty"`
	// Checks for unused import statements.
	UnusedImports *bool `form:"UnusedImports,omitempty" json:"UnusedImports,omitempty" xml:"UnusedImports,omitempty"`
	// Checks that long constants are defined with an upper ell.
	UpperEll *bool `form:"UpperEll,omitempty" json:"UpperEll,omitempty" xml:"UpperEll,omitempty"`
	// Checks the distance between declaration of variable and its first usage.
	VariableDeclarationUsageDistance *bool `form:"VariableDeclarationUsageDistance,omitempty" json:"VariableDeclarationUsageDistance,omitempty" xml:"VariableDeclarationUsageDistance,omitempty"`
	// Checks visibility of class members.
	VisibilityModifier *bool `form:"VisibilityModifier,omitempty" json:"VisibilityModifier,omitempty" xml:"VisibilityModifier,omitempty"`
	// Checks that a token is followed by whitespace, with the exception that it does not check for whitespace after the semicolon of an empty for iterator.
	WhitespaceAfter *bool `form:"WhitespaceAfter,omitempty" json:"WhitespaceAfter,omitempty" xml:"WhitespaceAfter,omitempty"`
	// Checks that a token is surrounded by whitespace.
	WhitespaceAround *bool `form:"WhitespaceAround,omitempty" json:"WhitespaceAround,omitempty" xml:"WhitespaceAround,omitempty"`
	// Outputs a JavaDoc tag as information.
	WriteTag *bool `form:"WriteTag,omitempty" json:"WriteTag,omitempty" xml:"WriteTag,omitempty"`
}

// Publicize creates Checkstyle from checkstyle
func (ut *checkstyle) Publicize() *Checkstyle {
	var pub Checkstyle
	if ut.AbbreviationAsWordInName != nil {
		pub.AbbreviationAsWordInName = ut.AbbreviationAsWordInName
	}
	if ut.AbstractClassName != nil {
		pub.AbstractClassName = ut.AbstractClassName
	}
	if ut.AnnotationLocation != nil {
		pub.AnnotationLocation = ut.AnnotationLocation
	}
	if ut.AnnotationUseStyle != nil {
		pub.AnnotationUseStyle = ut.AnnotationUseStyle
	}
	if ut.AnonInnerLength != nil {
		pub.AnonInnerLength = ut.AnonInnerLength
	}
	if ut.ArrayTrailingComma != nil {
		pub.ArrayTrailingComma = ut.ArrayTrailingComma
	}
	if ut.ArrayTypeStyle != nil {
		pub.ArrayTypeStyle = ut.ArrayTypeStyle
	}
	if ut.AtclauseOrder != nil {
		pub.AtclauseOrder = ut.AtclauseOrder
	}
	if ut.AvoidEscapedUnicodeCharacters != nil {
		pub.AvoidEscapedUnicodeCharacters = ut.AvoidEscapedUnicodeCharacters
	}
	if ut.AvoidInlineConditionals != nil {
		pub.AvoidInlineConditionals = ut.AvoidInlineConditionals
	}
	if ut.AvoidNestedBlocks != nil {
		pub.AvoidNestedBlocks = ut.AvoidNestedBlocks
	}
	if ut.AvoidStarImport != nil {
		pub.AvoidStarImport = ut.AvoidStarImport
	}
	if ut.AvoidStaticImport != nil {
		pub.AvoidStaticImport = ut.AvoidStaticImport
	}
	if ut.BooleanExpressionComplexity != nil {
		pub.BooleanExpressionComplexity = ut.BooleanExpressionComplexity
	}
	if ut.CatchParameterName != nil {
		pub.CatchParameterName = ut.CatchParameterName
	}
	if ut.ClassDataAbstractionCoupling != nil {
		pub.ClassDataAbstractionCoupling = ut.ClassDataAbstractionCoupling
	}
	if ut.ClassFanOutComplexity != nil {
		pub.ClassFanOutComplexity = ut.ClassFanOutComplexity
	}
	if ut.ClassTypeParameterName != nil {
		pub.ClassTypeParameterName = ut.ClassTypeParameterName
	}
	if ut.CommentsIndentation != nil {
		pub.CommentsIndentation = ut.CommentsIndentation
	}
	if ut.ConstantName != nil {
		pub.ConstantName = ut.ConstantName
	}
	if ut.CovariantEquals != nil {
		pub.CovariantEquals = ut.CovariantEquals
	}
	if ut.CustomImportOrder != nil {
		pub.CustomImportOrder = ut.CustomImportOrder
	}
	if ut.CyclomaticComplexity != nil {
		pub.CyclomaticComplexity = ut.CyclomaticComplexity
	}
	if ut.DeclarationOrder != nil {
		pub.DeclarationOrder = ut.DeclarationOrder
	}
	if ut.DefaultComesLast != nil {
		pub.DefaultComesLast = ut.DefaultComesLast
	}
	if ut.DescendantToken != nil {
		pub.DescendantToken = ut.DescendantToken
	}
	if ut.DesignForExtension != nil {
		pub.DesignForExtension = ut.DesignForExtension
	}
	if ut.EmptyBlock != nil {
		pub.EmptyBlock = ut.EmptyBlock
	}
	if ut.EmptyCatchBlock != nil {
		pub.EmptyCatchBlock = ut.EmptyCatchBlock
	}
	if ut.EmptyForInitializerPad != nil {
		pub.EmptyForInitializerPad = ut.EmptyForInitializerPad
	}
	if ut.EmptyForIteratorPad != nil {
		pub.EmptyForIteratorPad = ut.EmptyForIteratorPad
	}
	if ut.EmptyLineSeparator != nil {
		pub.EmptyLineSeparator = ut.EmptyLineSeparator
	}
	if ut.EmptyStatement != nil {
		pub.EmptyStatement = ut.EmptyStatement
	}
	if ut.EqualsAvoidNull != nil {
		pub.EqualsAvoidNull = ut.EqualsAvoidNull
	}
	if ut.EqualsHashCode != nil {
		pub.EqualsHashCode = ut.EqualsHashCode
	}
	if ut.ExecutableStatementCount != nil {
		pub.ExecutableStatementCount = ut.ExecutableStatementCount
	}
	if ut.ExplicitInitialization != nil {
		pub.ExplicitInitialization = ut.ExplicitInitialization
	}
	if ut.FallThrough != nil {
		pub.FallThrough = ut.FallThrough
	}
	if ut.FileLength != nil {
		pub.FileLength = ut.FileLength
	}
	if ut.FileTabCharacter != nil {
		pub.FileTabCharacter = ut.FileTabCharacter
	}
	if ut.FinalClass != nil {
		pub.FinalClass = ut.FinalClass
	}
	if ut.FinalLocalVariable != nil {
		pub.FinalLocalVariable = ut.FinalLocalVariable
	}
	if ut.FinalParameters != nil {
		pub.FinalParameters = ut.FinalParameters
	}
	if ut.GenericWhitespace != nil {
		pub.GenericWhitespace = ut.GenericWhitespace
	}
	if ut.Header != nil {
		pub.Header = ut.Header
	}
	if ut.HiddenField != nil {
		pub.HiddenField = ut.HiddenField
	}
	if ut.HideUtilityClassConstructor != nil {
		pub.HideUtilityClassConstructor = ut.HideUtilityClassConstructor
	}
	if ut.IllegalCatch != nil {
		pub.IllegalCatch = ut.IllegalCatch
	}
	if ut.IllegalImport != nil {
		pub.IllegalImport = ut.IllegalImport
	}
	if ut.IllegalInstantiation != nil {
		pub.IllegalInstantiation = ut.IllegalInstantiation
	}
	if ut.IllegalThrows != nil {
		pub.IllegalThrows = ut.IllegalThrows
	}
	if ut.IllegalToken != nil {
		pub.IllegalToken = ut.IllegalToken
	}
	if ut.IllegalTokenText != nil {
		pub.IllegalTokenText = ut.IllegalTokenText
	}
	if ut.IllegalType != nil {
		pub.IllegalType = ut.IllegalType
	}
	if ut.ImportControl != nil {
		pub.ImportControl = ut.ImportControl
	}
	if ut.ImportOrder != nil {
		pub.ImportOrder = ut.ImportOrder
	}
	if ut.Indentation != nil {
		pub.Indentation = ut.Indentation
	}
	if ut.InnerAssignment != nil {
		pub.InnerAssignment = ut.InnerAssignment
	}
	if ut.InnerTypeLast != nil {
		pub.InnerTypeLast = ut.InnerTypeLast
	}
	if ut.InterfaceIsType != nil {
		pub.InterfaceIsType = ut.InterfaceIsType
	}
	if ut.InterfaceTypeParameterName != nil {
		pub.InterfaceTypeParameterName = ut.InterfaceTypeParameterName
	}
	if ut.JavaNCSS != nil {
		pub.JavaNCSS = ut.JavaNCSS
	}
	if ut.JavadocMethod != nil {
		pub.JavadocMethod = ut.JavadocMethod
	}
	if ut.JavadocPackage != nil {
		pub.JavadocPackage = ut.JavadocPackage
	}
	if ut.JavadocParagraph != nil {
		pub.JavadocParagraph = ut.JavadocParagraph
	}
	if ut.JavadocStyle != nil {
		pub.JavadocStyle = ut.JavadocStyle
	}
	if ut.JavadocTagContinuationIndentation != nil {
		pub.JavadocTagContinuationIndentation = ut.JavadocTagContinuationIndentation
	}
	if ut.JavadocType != nil {
		pub.JavadocType = ut.JavadocType
	}
	if ut.JavadocVariable != nil {
		pub.JavadocVariable = ut.JavadocVariable
	}
	if ut.LeftCurly != nil {
		pub.LeftCurly = ut.LeftCurly
	}
	if ut.LineLength != nil {
		pub.LineLength = ut.LineLength
	}
	if ut.LocalFinalVariableName != nil {
		pub.LocalFinalVariableName = ut.LocalFinalVariableName
	}
	if ut.LocalVariableName != nil {
		pub.LocalVariableName = ut.LocalVariableName
	}
	if ut.MagicNumber != nil {
		pub.MagicNumber = ut.MagicNumber
	}
	if ut.MemberName != nil {
		pub.MemberName = ut.MemberName
	}
	if ut.MethodCount != nil {
		pub.MethodCount = ut.MethodCount
	}
	if ut.MethodLength != nil {
		pub.MethodLength = ut.MethodLength
	}
	if ut.MethodName != nil {
		pub.MethodName = ut.MethodName
	}
	if ut.MethodParamPad != nil {
		pub.MethodParamPad = ut.MethodParamPad
	}
	if ut.MethodTypeParameterName != nil {
		pub.MethodTypeParameterName = ut.MethodTypeParameterName
	}
	if ut.MissingCtor != nil {
		pub.MissingCtor = ut.MissingCtor
	}
	if ut.MissingDeprecated != nil {
		pub.MissingDeprecated = ut.MissingDeprecated
	}
	if ut.MissingOverride != nil {
		pub.MissingOverride = ut.MissingOverride
	}
	if ut.MissingSwitchDefault != nil {
		pub.MissingSwitchDefault = ut.MissingSwitchDefault
	}
	if ut.ModifiedControlVariable != nil {
		pub.ModifiedControlVariable = ut.ModifiedControlVariable
	}
	if ut.ModifierOrder != nil {
		pub.ModifierOrder = ut.ModifierOrder
	}
	if ut.MultipleStringLiterals != nil {
		pub.MultipleStringLiterals = ut.MultipleStringLiterals
	}
	if ut.MultipleVariableDeclarations != nil {
		pub.MultipleVariableDeclarations = ut.MultipleVariableDeclarations
	}
	if ut.MutableException != nil {
		pub.MutableException = ut.MutableException
	}
	if ut.NPathComplexity != nil {
		pub.NPathComplexity = ut.NPathComplexity
	}
	if ut.NeedBraces != nil {
		pub.NeedBraces = ut.NeedBraces
	}
	if ut.NestedForDepth != nil {
		pub.NestedForDepth = ut.NestedForDepth
	}
	if ut.NestedIfDepth != nil {
		pub.NestedIfDepth = ut.NestedIfDepth
	}
	if ut.NestedTryDepth != nil {
		pub.NestedTryDepth = ut.NestedTryDepth
	}
	if ut.NewlineAtEndOfFile != nil {
		pub.NewlineAtEndOfFile = ut.NewlineAtEndOfFile
	}
	if ut.NoClone != nil {
		pub.NoClone = ut.NoClone
	}
	if ut.NoFinalizer != nil {
		pub.NoFinalizer = ut.NoFinalizer
	}
	if ut.NoLineWrap != nil {
		pub.NoLineWrap = ut.NoLineWrap
	}
	if ut.NoWhitespaceAfter != nil {
		pub.NoWhitespaceAfter = ut.NoWhitespaceAfter
	}
	if ut.NoWhitespaceBefore != nil {
		pub.NoWhitespaceBefore = ut.NoWhitespaceBefore
	}
	if ut.NonEmptyAtclauseDescription != nil {
		pub.NonEmptyAtclauseDescription = ut.NonEmptyAtclauseDescription
	}
	if ut.OneStatementPerLine != nil {
		pub.OneStatementPerLine = ut.OneStatementPerLine
	}
	if ut.OneTopLevelClass != nil {
		pub.OneTopLevelClass = ut.OneTopLevelClass
	}
	if ut.OperatorWrap != nil {
		pub.OperatorWrap = ut.OperatorWrap
	}
	if ut.OuterTypeFilename != nil {
		pub.OuterTypeFilename = ut.OuterTypeFilename
	}
	if ut.OuterTypeNumber != nil {
		pub.OuterTypeNumber = ut.OuterTypeNumber
	}
	if ut.OverloadMethodsDeclarationOrder != nil {
		pub.OverloadMethodsDeclarationOrder = ut.OverloadMethodsDeclarationOrder
	}
	if ut.PackageAnnotation != nil {
		pub.PackageAnnotation = ut.PackageAnnotation
	}
	if ut.PackageDeclaration != nil {
		pub.PackageDeclaration = ut.PackageDeclaration
	}
	if ut.PackageName != nil {
		pub.PackageName = ut.PackageName
	}
	if ut.ParameterAssignment != nil {
		pub.ParameterAssignment = ut.ParameterAssignment
	}
	if ut.ParameterName != nil {
		pub.ParameterName = ut.ParameterName
	}
	if ut.ParameterNumber != nil {
		pub.ParameterNumber = ut.ParameterNumber
	}
	if ut.ParenPad != nil {
		pub.ParenPad = ut.ParenPad
	}
	if ut.RedundantImport != nil {
		pub.RedundantImport = ut.RedundantImport
	}
	if ut.RedundantModifier != nil {
		pub.RedundantModifier = ut.RedundantModifier
	}
	if ut.Regexp != nil {
		pub.Regexp = ut.Regexp
	}
	if ut.RegexpHeader != nil {
		pub.RegexpHeader = ut.RegexpHeader
	}
	if ut.RegexpMultiline != nil {
		pub.RegexpMultiline = ut.RegexpMultiline
	}
	if ut.RegexpOnFilename != nil {
		pub.RegexpOnFilename = ut.RegexpOnFilename
	}
	if ut.RegexpSingleline != nil {
		pub.RegexpSingleline = ut.RegexpSingleline
	}
	if ut.RegexpSinglelineJava != nil {
		pub.RegexpSinglelineJava = ut.RegexpSinglelineJava
	}
	if ut.RequireThis != nil {
		pub.RequireThis = ut.RequireThis
	}
	if ut.ReturnCount != nil {
		pub.ReturnCount = ut.ReturnCount
	}
	if ut.RightCurly != nil {
		pub.RightCurly = ut.RightCurly
	}
	if ut.SeparatorWrap != nil {
		pub.SeparatorWrap = ut.SeparatorWrap
	}
	if ut.SimplifyBooleanExpression != nil {
		pub.SimplifyBooleanExpression = ut.SimplifyBooleanExpression
	}
	if ut.SimplifyBooleanReturn != nil {
		pub.SimplifyBooleanReturn = ut.SimplifyBooleanReturn
	}
	if ut.SingleLineJavadoc != nil {
		pub.SingleLineJavadoc = ut.SingleLineJavadoc
	}
	if ut.SingleSpaceSeparator != nil {
		pub.SingleSpaceSeparator = ut.SingleSpaceSeparator
	}
	if ut.StaticVariableName != nil {
		pub.StaticVariableName = ut.StaticVariableName
	}
	if ut.StringLiteralEquality != nil {
		pub.StringLiteralEquality = ut.StringLiteralEquality
	}
	if ut.SummaryJavadoc != nil {
		pub.SummaryJavadoc = ut.SummaryJavadoc
	}
	if ut.SuperClone != nil {
		pub.SuperClone = ut.SuperClone
	}
	if ut.SuperFinalize != nil {
		pub.SuperFinalize = ut.SuperFinalize
	}
	if ut.SuppressWarnings != nil {
		pub.SuppressWarnings = ut.SuppressWarnings
	}
	if ut.SuppressWarningsHolder != nil {
		pub.SuppressWarningsHolder = ut.SuppressWarningsHolder
	}
	if ut.ThrowsCount != nil {
		pub.ThrowsCount = ut.ThrowsCount
	}
	if ut.TodoComment != nil {
		pub.TodoComment = ut.TodoComment
	}
	if ut.TrailingComment != nil {
		pub.TrailingComment = ut.TrailingComment
	}
	if ut.Translation != nil {
		pub.Translation = ut.Translation
	}
	if ut.TypeName != nil {
		pub.TypeName = ut.TypeName
	}
	if ut.TypecastParenPad != nil {
		pub.TypecastParenPad = ut.TypecastParenPad
	}
	if ut.UncommentedMain != nil {
		pub.UncommentedMain = ut.UncommentedMain
	}
	if ut.UniqueProperties != nil {
		pub.UniqueProperties = ut.UniqueProperties
	}
	if ut.UnnecessaryParentheses != nil {
		pub.UnnecessaryParentheses = ut.UnnecessaryParentheses
	}
	if ut.UnusedImports != nil {
		pub.UnusedImports = ut.UnusedImports
	}
	if ut.UpperEll != nil {
		pub.UpperEll = ut.UpperEll
	}
	if ut.VariableDeclarationUsageDistance != nil {
		pub.VariableDeclarationUsageDistance = ut.VariableDeclarationUsageDistance
	}
	if ut.VisibilityModifier != nil {
		pub.VisibilityModifier = ut.VisibilityModifier
	}
	if ut.WhitespaceAfter != nil {
		pub.WhitespaceAfter = ut.WhitespaceAfter
	}
	if ut.WhitespaceAround != nil {
		pub.WhitespaceAround = ut.WhitespaceAround
	}
	if ut.WriteTag != nil {
		pub.WriteTag = ut.WriteTag
	}
	return &pub
}

// Description of which Checkstyle lints are checked.
type Checkstyle struct {
	// The Check validate abbreviations(consecutive capital letters) length in identifier name, it also allow in enforce camel case naming.
	AbbreviationAsWordInName *bool `form:"AbbreviationAsWordInName,omitempty" json:"AbbreviationAsWordInName,omitempty" xml:"AbbreviationAsWordInName,omitempty"`
	// Ensures that the names of abstract classes conforming to some regular expression.
	AbstractClassName *bool `form:"AbstractClassName,omitempty" json:"AbstractClassName,omitempty" xml:"AbstractClassName,omitempty"`
	// Check location of annotation on language elements.
	AnnotationLocation *bool `form:"AnnotationLocation,omitempty" json:"AnnotationLocation,omitempty" xml:"AnnotationLocation,omitempty"`
	// This check controls the style with the usage of annotations.
	AnnotationUseStyle *bool `form:"AnnotationUseStyle,omitempty" json:"AnnotationUseStyle,omitempty" xml:"AnnotationUseStyle,omitempty"`
	// Checks for long anonymous inner classes.
	AnonInnerLength *bool `form:"AnonInnerLength,omitempty" json:"AnonInnerLength,omitempty" xml:"AnonInnerLength,omitempty"`
	// Checks if array initialization contains optional trailing comma.
	ArrayTrailingComma *bool `form:"ArrayTrailingComma,omitempty" json:"ArrayTrailingComma,omitempty" xml:"ArrayTrailingComma,omitempty"`
	// Checks the style of array type definitions.
	ArrayTypeStyle *bool `form:"ArrayTypeStyle,omitempty" json:"ArrayTypeStyle,omitempty" xml:"ArrayTypeStyle,omitempty"`
	// Checks the order of at-clauses.
	AtclauseOrder *bool `form:"AtclauseOrder,omitempty" json:"AtclauseOrder,omitempty" xml:"AtclauseOrder,omitempty"`
	// Restrict using Unicode escapes.
	AvoidEscapedUnicodeCharacters *bool `form:"AvoidEscapedUnicodeCharacters,omitempty" json:"AvoidEscapedUnicodeCharacters,omitempty" xml:"AvoidEscapedUnicodeCharacters,omitempty"`
	// Detects inline conditionals.
	AvoidInlineConditionals *bool `form:"AvoidInlineConditionals,omitempty" json:"AvoidInlineConditionals,omitempty" xml:"AvoidInlineConditionals,omitempty"`
	// Finds nested blocks.
	AvoidNestedBlocks *bool `form:"AvoidNestedBlocks,omitempty" json:"AvoidNestedBlocks,omitempty" xml:"AvoidNestedBlocks,omitempty"`
	// Check that finds import statements that use the * notation.
	AvoidStarImport *bool `form:"AvoidStarImport,omitempty" json:"AvoidStarImport,omitempty" xml:"AvoidStarImport,omitempty"`
	// Check that finds static imports.
	AvoidStaticImport *bool `form:"AvoidStaticImport,omitempty" json:"AvoidStaticImport,omitempty" xml:"AvoidStaticImport,omitempty"`
	// Restricts nested boolean operators (&&, ||, &, | and ^) to a specified depth (default = 3).
	BooleanExpressionComplexity *bool `form:"BooleanExpressionComplexity,omitempty" json:"BooleanExpressionComplexity,omitempty" xml:"BooleanExpressionComplexity,omitempty"`
	// Checks that catch parameter names conform to a format specified by the format property.
	CatchParameterName *bool `form:"CatchParameterName,omitempty" json:"CatchParameterName,omitempty" xml:"CatchParameterName,omitempty"`
	// This metric measures the number of instantiations of other classes within the given class.
	ClassDataAbstractionCoupling *bool `form:"ClassDataAbstractionCoupling,omitempty" json:"ClassDataAbstractionCoupling,omitempty" xml:"ClassDataAbstractionCoupling,omitempty"`
	// The number of other classes a given class relies on.
	ClassFanOutComplexity *bool `form:"ClassFanOutComplexity,omitempty" json:"ClassFanOutComplexity,omitempty" xml:"ClassFanOutComplexity,omitempty"`
	// Checks that class type parameter names conform to a format specified by the format property.
	ClassTypeParameterName *bool `form:"ClassTypeParameterName,omitempty" json:"ClassTypeParameterName,omitempty" xml:"ClassTypeParameterName,omitempty"`
	// Controls the indentation between comments and surrounding code.
	CommentsIndentation *bool `form:"CommentsIndentation,omitempty" json:"CommentsIndentation,omitempty" xml:"CommentsIndentation,omitempty"`
	// Checks that constant names conform to a format specified by the format property.
	ConstantName *bool `form:"ConstantName,omitempty" json:"ConstantName,omitempty" xml:"ConstantName,omitempty"`
	// Checks that if a class defines a covariant method equals, then it defines method equals(java.lang.Object).
	CovariantEquals *bool `form:"CovariantEquals,omitempty" json:"CovariantEquals,omitempty" xml:"CovariantEquals,omitempty"`
	// Checks that the groups of import declarations appear in the order specified by the user.
	CustomImportOrder *bool `form:"CustomImportOrder,omitempty" json:"CustomImportOrder,omitempty" xml:"CustomImportOrder,omitempty"`
	// Checks cyclomatic complexity against a specified limit.
	CyclomaticComplexity *bool `form:"CyclomaticComplexity,omitempty" json:"CyclomaticComplexity,omitempty" xml:"CyclomaticComplexity,omitempty"`
	// Checks that the parts of a class or interface declaration appear in the order suggested by the Code Conventions for the Java Programming Language.
	DeclarationOrder *bool `form:"DeclarationOrder,omitempty" json:"DeclarationOrder,omitempty" xml:"DeclarationOrder,omitempty"`
	// Check that the default is after all the cases in a switch statement.
	DefaultComesLast *bool `form:"DefaultComesLast,omitempty" json:"DefaultComesLast,omitempty" xml:"DefaultComesLast,omitempty"`
	// Checks for restricted tokens beneath other tokens.
	DescendantToken *bool `form:"DescendantToken,omitempty" json:"DescendantToken,omitempty" xml:"DescendantToken,omitempty"`
	// Checks that classes are designed for inheritance.
	DesignForExtension *bool `form:"DesignForExtension,omitempty" json:"DesignForExtension,omitempty" xml:"DesignForExtension,omitempty"`
	// Checks for empty blocks.
	EmptyBlock *bool `form:"EmptyBlock,omitempty" json:"EmptyBlock,omitempty" xml:"EmptyBlock,omitempty"`
	// Checks for empty catch blocks with few options to skip violation.
	EmptyCatchBlock *bool `form:"EmptyCatchBlock,omitempty" json:"EmptyCatchBlock,omitempty" xml:"EmptyCatchBlock,omitempty"`
	// Checks the padding of an empty for initializer; that is whether a space is required at an empty for initializer, or such spaces are forbidden.
	EmptyForInitializerPad *bool `form:"EmptyForInitializerPad,omitempty" json:"EmptyForInitializerPad,omitempty" xml:"EmptyForInitializerPad,omitempty"`
	// Checks the padding of an empty for iterator; that is whether a space is required at an empty for iterator, or such spaces are forbidden.
	EmptyForIteratorPad *bool `form:"EmptyForIteratorPad,omitempty" json:"EmptyForIteratorPad,omitempty" xml:"EmptyForIteratorPad,omitempty"`
	// Checks for blank line separators.
	EmptyLineSeparator *bool `form:"EmptyLineSeparator,omitempty" json:"EmptyLineSeparator,omitempty" xml:"EmptyLineSeparator,omitempty"`
	// Detects empty statements (standalone ';').
	EmptyStatement *bool `form:"EmptyStatement,omitempty" json:"EmptyStatement,omitempty" xml:"EmptyStatement,omitempty"`
	// Checks that any combination of String literals is on the left side of an equals() comparison.
	EqualsAvoidNull *bool `form:"EqualsAvoidNull,omitempty" json:"EqualsAvoidNull,omitempty" xml:"EqualsAvoidNull,omitempty"`
	// Checks that classes that override equals() also override hashCode().
	EqualsHashCode *bool `form:"EqualsHashCode,omitempty" json:"EqualsHashCode,omitempty" xml:"EqualsHashCode,omitempty"`
	// Restricts the number of executable statements to a specified limit (default = 30).
	ExecutableStatementCount *bool `form:"ExecutableStatementCount,omitempty" json:"ExecutableStatementCount,omitempty" xml:"ExecutableStatementCount,omitempty"`
	// Checks if any class or object member explicitly initialized to default for its type value (null for object references, zero for numeric types and char and false for boolean.
	ExplicitInitialization *bool `form:"ExplicitInitialization,omitempty" json:"ExplicitInitialization,omitempty" xml:"ExplicitInitialization,omitempty"`
	// Checks for fall through in switch statements Finds locations where a case contains Java code - but lacks a break, return, throw or continue statement.
	FallThrough *bool `form:"FallThrough,omitempty" json:"FallThrough,omitempty" xml:"FallThrough,omitempty"`
	// Checks for long source files.
	FileLength *bool `form:"FileLength,omitempty" json:"FileLength,omitempty" xml:"FileLength,omitempty"`
	// Checks to see if a file contains a tab character.
	FileTabCharacter *bool `form:"FileTabCharacter,omitempty" json:"FileTabCharacter,omitempty" xml:"FileTabCharacter,omitempty"`
	// Checks that class which has only private constructors is declared as final.
	FinalClass *bool `form:"FinalClass,omitempty" json:"FinalClass,omitempty" xml:"FinalClass,omitempty"`
	// Ensures that local variables that never get their values changed, must be declared final.
	FinalLocalVariable *bool `form:"FinalLocalVariable,omitempty" json:"FinalLocalVariable,omitempty" xml:"FinalLocalVariable,omitempty"`
	// Check that method/constructor/catch/foreach parameters are final.
	FinalParameters *bool `form:"FinalParameters,omitempty" json:"FinalParameters,omitempty" xml:"FinalParameters,omitempty"`
	// Checks that the whitespace around the Generic tokens < and > are correct to the typical convention.
	GenericWhitespace *bool `form:"GenericWhitespace,omitempty" json:"GenericWhitespace,omitempty" xml:"GenericWhitespace,omitempty"`
	// Checks the header of the source against a fixed header file.
	Header *bool `form:"Header,omitempty" json:"Header,omitempty" xml:"Header,omitempty"`
	// Checks that a local variable or a parameter does not shadow a field that is defined in the same class.
	HiddenField *bool `form:"HiddenField,omitempty" json:"HiddenField,omitempty" xml:"HiddenField,omitempty"`
	// Make sure that utility classes (classes that contain only static methods) do not have a public constructor.
	HideUtilityClassConstructor *bool `form:"HideUtilityClassConstructor,omitempty" json:"HideUtilityClassConstructor,omitempty" xml:"HideUtilityClassConstructor,omitempty"`
	// Catching java.lang.Exception, java.lang.Error or java.lang.RuntimeException is almost never acceptable.
	IllegalCatch *bool `form:"IllegalCatch,omitempty" json:"IllegalCatch,omitempty" xml:"IllegalCatch,omitempty"`
	// Checks for imports from a set of illegal packages.
	IllegalImport *bool `form:"IllegalImport,omitempty" json:"IllegalImport,omitempty" xml:"IllegalImport,omitempty"`
	// Checks for illegal instantiations where a factory method is preferred.
	IllegalInstantiation *bool `form:"IllegalInstantiation,omitempty" json:"IllegalInstantiation,omitempty" xml:"IllegalInstantiation,omitempty"`
	// Throwing java.lang.Error or java.lang.RuntimeException is almost never acceptable.
	IllegalThrows *bool `form:"IllegalThrows,omitempty" json:"IllegalThrows,omitempty" xml:"IllegalThrows,omitempty"`
	// Checks for illegal tokens.
	IllegalToken *bool `form:"IllegalToken,omitempty" json:"IllegalToken,omitempty" xml:"IllegalToken,omitempty"`
	// Checks for illegal token text.
	IllegalTokenText *bool `form:"IllegalTokenText,omitempty" json:"IllegalTokenText,omitempty" xml:"IllegalTokenText,omitempty"`
	// Checks that particular class are never used as types in variable declarations, return values or parameters.
	IllegalType *bool `form:"IllegalType,omitempty" json:"IllegalType,omitempty" xml:"IllegalType,omitempty"`
	// Check that controls what packages can be imported in each package.
	ImportControl *bool `form:"ImportControl,omitempty" json:"ImportControl,omitempty" xml:"ImportControl,omitempty"`
	// Ensures that groups of imports come in a specific order.
	ImportOrder *bool `form:"ImportOrder,omitempty" json:"ImportOrder,omitempty" xml:"ImportOrder,omitempty"`
	// Checks correct indentation of Java Code.
	Indentation *bool `form:"Indentation,omitempty" json:"Indentation,omitempty" xml:"Indentation,omitempty"`
	// Checks for assignments in subexpressions, such as in String s = Integer.toString(i = 2);.
	InnerAssignment *bool `form:"InnerAssignment,omitempty" json:"InnerAssignment,omitempty" xml:"InnerAssignment,omitempty"`
	// Check nested (internal) classes/interfaces are declared at the bottom of the class after all method and field declarations.
	InnerTypeLast *bool `form:"InnerTypeLast,omitempty" json:"InnerTypeLast,omitempty" xml:"InnerTypeLast,omitempty"`
	// Implements Bloch, Effective Java, Item 17 - Use Interfaces only to define types.
	InterfaceIsType *bool `form:"InterfaceIsType,omitempty" json:"InterfaceIsType,omitempty" xml:"InterfaceIsType,omitempty"`
	// Checks that interface type parameter names conform to a format specified by the format property.
	InterfaceTypeParameterName *bool `form:"InterfaceTypeParameterName,omitempty" json:"InterfaceTypeParameterName,omitempty" xml:"InterfaceTypeParameterName,omitempty"`
	// This check calculates the Non Commenting Source Statements (NCSS) metric for Java source files and methods.
	JavaNCSS *bool `form:"JavaNCSS,omitempty" json:"JavaNCSS,omitempty" xml:"JavaNCSS,omitempty"`
	// Checks the Javadoc of a method or constructor.
	JavadocMethod *bool `form:"JavadocMethod,omitempty" json:"JavadocMethod,omitempty" xml:"JavadocMethod,omitempty"`
	// Checks that all packages have a package documentation.
	JavadocPackage *bool `form:"JavadocPackage,omitempty" json:"JavadocPackage,omitempty" xml:"JavadocPackage,omitempty"`
	// Checks Javadoc paragraphs.
	JavadocParagraph *bool `form:"JavadocParagraph,omitempty" json:"JavadocParagraph,omitempty" xml:"JavadocParagraph,omitempty"`
	// Custom Checkstyle Check to validate Javadoc.
	JavadocStyle *bool `form:"JavadocStyle,omitempty" json:"JavadocStyle,omitempty" xml:"JavadocStyle,omitempty"`
	// Checks the indentation of the continuation lines in at-clauses.
	JavadocTagContinuationIndentation *bool `form:"JavadocTagContinuationIndentation,omitempty" json:"JavadocTagContinuationIndentation,omitempty" xml:"JavadocTagContinuationIndentation,omitempty"`
	// Checks the Javadoc of a type.
	JavadocType *bool `form:"JavadocType,omitempty" json:"JavadocType,omitempty" xml:"JavadocType,omitempty"`
	// Checks that a variable has Javadoc comment.
	JavadocVariable *bool `form:"JavadocVariable,omitempty" json:"JavadocVariable,omitempty" xml:"JavadocVariable,omitempty"`
	// Checks the placement of left curly braces on types, methods and other blocks:
	LeftCurly *bool `form:"LeftCurly,omitempty" json:"LeftCurly,omitempty" xml:"LeftCurly,omitempty"`
	// Checks for long lines.
	LineLength *bool `form:"LineLength,omitempty" json:"LineLength,omitempty" xml:"LineLength,omitempty"`
	// Checks that local final variable names conform to a format specified by the format property.
	LocalFinalVariableName *bool `form:"LocalFinalVariableName,omitempty" json:"LocalFinalVariableName,omitempty" xml:"LocalFinalVariableName,omitempty"`
	// Checks that local, non-final variable names conform to a format specified by the format property.
	LocalVariableName *bool `form:"LocalVariableName,omitempty" json:"LocalVariableName,omitempty" xml:"LocalVariableName,omitempty"`
	// Checks for magic numbers.
	MagicNumber *bool `form:"MagicNumber,omitempty" json:"MagicNumber,omitempty" xml:"MagicNumber,omitempty"`
	// Checks that instance variable names conform to a format specified by the format property.
	MemberName *bool `form:"MemberName,omitempty" json:"MemberName,omitempty" xml:"MemberName,omitempty"`
	// Checks the number of methods declared in each type.
	MethodCount *bool `form:"MethodCount,omitempty" json:"MethodCount,omitempty" xml:"MethodCount,omitempty"`
	// Checks for long methods.
	MethodLength *bool `form:"MethodLength,omitempty" json:"MethodLength,omitempty" xml:"MethodLength,omitempty"`
	// Checks that method names conform to a format specified by the format property.
	MethodName *bool `form:"MethodName,omitempty" json:"MethodName,omitempty" xml:"MethodName,omitempty"`
	// Checks the padding between the identifier of a method definition, constructor definition, method call, or constructor invocation; and the left parenthesis of the parameter list.
	MethodParamPad *bool `form:"MethodParamPad,omitempty" json:"MethodParamPad,omitempty" xml:"MethodParamPad,omitempty"`
	// Checks that class type parameter names conform to a format specified by the format property.
	MethodTypeParameterName *bool `form:"MethodTypeParameterName,omitempty" json:"MethodTypeParameterName,omitempty" xml:"MethodTypeParameterName,omitempty"`
	// Checks that classes (except abstract one) define a ctor and don't rely on the default one.
	MissingCtor *bool `form:"MissingCtor,omitempty" json:"MissingCtor,omitempty" xml:"MissingCtor,omitempty"`
	// This class is used to verify that both the java.lang.Deprecated annotation is present and the @deprecated Javadoc tag is present when either is present.
	MissingDeprecated *bool `form:"MissingDeprecated,omitempty" json:"MissingDeprecated,omitempty" xml:"MissingDeprecated,omitempty"`
	// This class is used to verify that the java.lang.Override annotation is present when the {@inheritDoc} javadoc tag is present.
	MissingOverride *bool `form:"MissingOverride,omitempty" json:"MissingOverride,omitempty" xml:"MissingOverride,omitempty"`
	// Checks that switch statement has 'default' clause.
	MissingSwitchDefault *bool `form:"MissingSwitchDefault,omitempty" json:"MissingSwitchDefault,omitempty" xml:"MissingSwitchDefault,omitempty"`
	// Check for ensuring that for loop control variables are not modified inside the for block.
	ModifiedControlVariable *bool `form:"ModifiedControlVariable,omitempty" json:"ModifiedControlVariable,omitempty" xml:"ModifiedControlVariable,omitempty"`
	// Checks that the order of modifiers conforms to the suggestions in the Java Language specification, sections 8.1.1, 8.3.1 and 8.4.3.
	ModifierOrder *bool `form:"ModifierOrder,omitempty" json:"ModifierOrder,omitempty" xml:"ModifierOrder,omitempty"`
	// Checks for multiple occurrences of the same string literal within a single file.
	MultipleStringLiterals *bool `form:"MultipleStringLiterals,omitempty" json:"MultipleStringLiterals,omitempty" xml:"MultipleStringLiterals,omitempty"`
	// Checks that each variable declaration is in its own statement and on its own line.
	MultipleVariableDeclarations *bool `form:"MultipleVariableDeclarations,omitempty" json:"MultipleVariableDeclarations,omitempty" xml:"MultipleVariableDeclarations,omitempty"`
	// Ensures that exceptions (defined as any class name conforming to some regular expression) are immutable.
	MutableException *bool `form:"MutableException,omitempty" json:"MutableException,omitempty" xml:"MutableException,omitempty"`
	// Checks the npath complexity against a specified limit (default = 200).
	NPathComplexity *bool `form:"NPathComplexity,omitempty" json:"NPathComplexity,omitempty" xml:"NPathComplexity,omitempty"`
	// Checks for braces around code blocks.
	NeedBraces *bool `form:"NeedBraces,omitempty" json:"NeedBraces,omitempty" xml:"NeedBraces,omitempty"`
	// Restricts nested for blocks to a specified depth (default = 1).
	NestedForDepth *bool `form:"NestedForDepth,omitempty" json:"NestedForDepth,omitempty" xml:"NestedForDepth,omitempty"`
	// Restricts nested if-else blocks to a specified depth (default = 1).
	NestedIfDepth *bool `form:"NestedIfDepth,omitempty" json:"NestedIfDepth,omitempty" xml:"NestedIfDepth,omitempty"`
	// Restricts nested try-catch-finally blocks to a specified depth (default = 1).
	NestedTryDepth *bool `form:"NestedTryDepth,omitempty" json:"NestedTryDepth,omitempty" xml:"NestedTryDepth,omitempty"`
	// Checks that there is a newline at the end of each file.
	NewlineAtEndOfFile *bool `form:"NewlineAtEndOfFile,omitempty" json:"NewlineAtEndOfFile,omitempty" xml:"NewlineAtEndOfFile,omitempty"`
	// Checks that the clone method is not overridden from the Object class.
	NoClone *bool `form:"NoClone,omitempty" json:"NoClone,omitempty" xml:"NoClone,omitempty"`
	// Checks that no method having zero parameters is defined using the name finalize.
	NoFinalizer *bool `form:"NoFinalizer,omitempty" json:"NoFinalizer,omitempty" xml:"NoFinalizer,omitempty"`
	// Checks that chosen statements are not line-wrapped.
	NoLineWrap *bool `form:"NoLineWrap,omitempty" json:"NoLineWrap,omitempty" xml:"NoLineWrap,omitempty"`
	// Checks that there is no whitespace after a token.
	NoWhitespaceAfter *bool `form:"NoWhitespaceAfter,omitempty" json:"NoWhitespaceAfter,omitempty" xml:"NoWhitespaceAfter,omitempty"`
	// Checks that there is no whitespace before a token.
	NoWhitespaceBefore *bool `form:"NoWhitespaceBefore,omitempty" json:"NoWhitespaceBefore,omitempty" xml:"NoWhitespaceBefore,omitempty"`
	// Checks that the at-clause tag is followed by description .
	NonEmptyAtclauseDescription *bool `form:"NonEmptyAtclauseDescription,omitempty" json:"NonEmptyAtclauseDescription,omitempty" xml:"NonEmptyAtclauseDescription,omitempty"`
	// Checks that there is only one statement per line.
	OneStatementPerLine *bool `form:"OneStatementPerLine,omitempty" json:"OneStatementPerLine,omitempty" xml:"OneStatementPerLine,omitempty"`
	// Checks that each top-level class, interfaces or enum resides in a source file of its own.
	OneTopLevelClass *bool `form:"OneTopLevelClass,omitempty" json:"OneTopLevelClass,omitempty" xml:"OneTopLevelClass,omitempty"`
	// Checks line wrapping for operators.
	OperatorWrap *bool `form:"OperatorWrap,omitempty" json:"OperatorWrap,omitempty" xml:"OperatorWrap,omitempty"`
	// Checks that the outer type name and the file name match.
	OuterTypeFilename *bool `form:"OuterTypeFilename,omitempty" json:"OuterTypeFilename,omitempty" xml:"OuterTypeFilename,omitempty"`
	// Checks for the number of defined types at the 'outer' level.
	OuterTypeNumber *bool `form:"OuterTypeNumber,omitempty" json:"OuterTypeNumber,omitempty" xml:"OuterTypeNumber,omitempty"`
	// Checks that overload methods are grouped together.
	OverloadMethodsDeclarationOrder *bool `form:"OverloadMethodsDeclarationOrder,omitempty" json:"OverloadMethodsDeclarationOrder,omitempty" xml:"OverloadMethodsDeclarationOrder,omitempty"`
	// This check makes sure that all package annotations are in the package-info.java file.
	PackageAnnotation *bool `form:"PackageAnnotation,omitempty" json:"PackageAnnotation,omitempty" xml:"PackageAnnotation,omitempty"`
	// Ensures there is a package declaration and (optionally) in the correct directory.
	PackageDeclaration *bool `form:"PackageDeclaration,omitempty" json:"PackageDeclaration,omitempty" xml:"PackageDeclaration,omitempty"`
	// Checks that package names conform to a format specified by the format property.
	PackageName *bool `form:"PackageName,omitempty" json:"PackageName,omitempty" xml:"PackageName,omitempty"`
	// Disallow assignment of parameters.
	ParameterAssignment *bool `form:"ParameterAssignment,omitempty" json:"ParameterAssignment,omitempty" xml:"ParameterAssignment,omitempty"`
	// Checks that parameter names conform to a format specified by the format property.
	ParameterName *bool `form:"ParameterName,omitempty" json:"ParameterName,omitempty" xml:"ParameterName,omitempty"`
	// Checks the number of parameters that a method or constructor has.
	ParameterNumber *bool `form:"ParameterNumber,omitempty" json:"ParameterNumber,omitempty" xml:"ParameterNumber,omitempty"`
	// Checks the padding of parentheses; that is whether a space is required after a left parenthesis and before a right parenthesis, or such spaces are forbidden, with the exception that it does not check for padding of the right parenthesis at an empty for iterator.
	ParenPad *bool `form:"ParenPad,omitempty" json:"ParenPad,omitempty" xml:"ParenPad,omitempty"`
	// Checks for imports that are redundant.
	RedundantImport *bool `form:"RedundantImport,omitempty" json:"RedundantImport,omitempty" xml:"RedundantImport,omitempty"`
	// Checks for redundant modifiers in interface and annotation definitions, final modifier on methods of final classes, inner interface declarations that are declared as static, non public class constructors and enum constructors, nested enum definitions that are declared as static.
	RedundantModifier *bool `form:"RedundantModifier,omitempty" json:"RedundantModifier,omitempty" xml:"RedundantModifier,omitempty"`
	// A check that makes sure that a specified pattern exists (or not) in the file.
	Regexp *bool `form:"Regexp,omitempty" json:"Regexp,omitempty" xml:"Regexp,omitempty"`
	// Checks the header of the source against a header file that contains a
	RegexpHeader *bool `form:"RegexpHeader,omitempty" json:"RegexpHeader,omitempty" xml:"RegexpHeader,omitempty"`
	// Implementation of a check that looks that matches across multiple lines in any file type.
	RegexpMultiline *bool `form:"RegexpMultiline,omitempty" json:"RegexpMultiline,omitempty" xml:"RegexpMultiline,omitempty"`
	// Implementation of a check that matches based on file and/or folder path.
	RegexpOnFilename *bool `form:"RegexpOnFilename,omitempty" json:"RegexpOnFilename,omitempty" xml:"RegexpOnFilename,omitempty"`
	// Implementation of a check that looks for a single line in any file type.
	RegexpSingleline *bool `form:"RegexpSingleline,omitempty" json:"RegexpSingleline,omitempty" xml:"RegexpSingleline,omitempty"`
	// Implementation of a check that looks for a single line in Java files.
	RegexpSinglelineJava *bool `form:"RegexpSinglelineJava,omitempty" json:"RegexpSinglelineJava,omitempty" xml:"RegexpSinglelineJava,omitempty"`
	// Checks that code doesn't rely on the 'this' default.
	RequireThis *bool `form:"RequireThis,omitempty" json:"RequireThis,omitempty" xml:"RequireThis,omitempty"`
	// Restricts return statements to a specified count (default = 2).
	ReturnCount *bool `form:"ReturnCount,omitempty" json:"ReturnCount,omitempty" xml:"ReturnCount,omitempty"`
	// Checks the placement of right curly braces.
	RightCurly *bool `form:"RightCurly,omitempty" json:"RightCurly,omitempty" xml:"RightCurly,omitempty"`
	// Checks line wrapping with separators.
	SeparatorWrap *bool `form:"SeparatorWrap,omitempty" json:"SeparatorWrap,omitempty" xml:"SeparatorWrap,omitempty"`
	// Checks for overly complicated boolean expressions.
	SimplifyBooleanExpression *bool `form:"SimplifyBooleanExpression,omitempty" json:"SimplifyBooleanExpression,omitempty" xml:"SimplifyBooleanExpression,omitempty"`
	// Checks for overly complicated boolean return statements.
	SimplifyBooleanReturn *bool `form:"SimplifyBooleanReturn,omitempty" json:"SimplifyBooleanReturn,omitempty" xml:"SimplifyBooleanReturn,omitempty"`
	// Checks that a JavaDoc block which can fit on a single line and doesn't contain at-clauses
	SingleLineJavadoc *bool `form:"SingleLineJavadoc,omitempty" json:"SingleLineJavadoc,omitempty" xml:"SingleLineJavadoc,omitempty"`
	// Checks that non-whitespace characters are separated by no more than one whitespace.
	SingleSpaceSeparator *bool `form:"SingleSpaceSeparator,omitempty" json:"SingleSpaceSeparator,omitempty" xml:"SingleSpaceSeparator,omitempty"`
	// Checks that static, non-final variable names conform to a format specified by the format property.
	StaticVariableName *bool `form:"StaticVariableName,omitempty" json:"StaticVariableName,omitempty" xml:"StaticVariableName,omitempty"`
	// Checks that string literals are not used with == or !=.
	StringLiteralEquality *bool `form:"StringLiteralEquality,omitempty" json:"StringLiteralEquality,omitempty" xml:"StringLiteralEquality,omitempty"`
	// Checks that Javadoc summary sentence does not contain phrases that are not recommended to use.
	SummaryJavadoc *bool `form:"SummaryJavadoc,omitempty" json:"SummaryJavadoc,omitempty" xml:"SummaryJavadoc,omitempty"`
	// Checks that an overriding clone() method invokes super.clone().
	SuperClone *bool `form:"SuperClone,omitempty" json:"SuperClone,omitempty" xml:"SuperClone,omitempty"`
	// Checks that an overriding finalize() method invokes super.finalize().
	SuperFinalize *bool `form:"SuperFinalize,omitempty" json:"SuperFinalize,omitempty" xml:"SuperFinalize,omitempty"`
	// This check allows you to specify what warnings that
	SuppressWarnings *bool `form:"SuppressWarnings,omitempty" json:"SuppressWarnings,omitempty" xml:"SuppressWarnings,omitempty"`
	// This check allows for finding code that should not be reported by Checkstyle
	SuppressWarningsHolder *bool `form:"SuppressWarningsHolder,omitempty" json:"SuppressWarningsHolder,omitempty" xml:"SuppressWarningsHolder,omitempty"`
	// Restricts throws statements to a specified count (default = 4).
	ThrowsCount *bool `form:"ThrowsCount,omitempty" json:"ThrowsCount,omitempty" xml:"ThrowsCount,omitempty"`
	// A check for TODO comments.
	TodoComment *bool `form:"TodoComment,omitempty" json:"TodoComment,omitempty" xml:"TodoComment,omitempty"`
	// The check to ensure that requires that comments be the only thing on a line.
	TrailingComment *bool `form:"TrailingComment,omitempty" json:"TrailingComment,omitempty" xml:"TrailingComment,omitempty"`
	// The TranslationCheck class helps to ensure the correct translation of code by checking property files for consistency regarding their keys.
	Translation *bool `form:"Translation,omitempty" json:"Translation,omitempty" xml:"Translation,omitempty"`
	// Checks that type names conform to a format specified by the format property.
	TypeName *bool `form:"TypeName,omitempty" json:"TypeName,omitempty" xml:"TypeName,omitempty"`
	// Checks the padding of parentheses for typecasts.
	TypecastParenPad *bool `form:"TypecastParenPad,omitempty" json:"TypecastParenPad,omitempty" xml:"TypecastParenPad,omitempty"`
	// Detects uncommented main methods.
	UncommentedMain *bool `form:"UncommentedMain,omitempty" json:"UncommentedMain,omitempty" xml:"UncommentedMain,omitempty"`
	// Detects duplicated keys in properties files.
	UniqueProperties *bool `form:"UniqueProperties,omitempty" json:"UniqueProperties,omitempty" xml:"UniqueProperties,omitempty"`
	// Checks if unnecessary parentheses are used in a statement or expression.
	UnnecessaryParentheses *bool `form:"UnnecessaryParentheses,omitempty" json:"UnnecessaryParentheses,omitempty" xml:"UnnecessaryParentheses,omitempty"`
	// Checks for unused import statements.
	UnusedImports *bool `form:"UnusedImports,omitempty" json:"UnusedImports,omitempty" xml:"UnusedImports,omitempty"`
	// Checks that long constants are defined with an upper ell.
	UpperEll *bool `form:"UpperEll,omitempty" json:"UpperEll,omitempty" xml:"UpperEll,omitempty"`
	// Checks the distance between declaration of variable and its first usage.
	VariableDeclarationUsageDistance *bool `form:"VariableDeclarationUsageDistance,omitempty" json:"VariableDeclarationUsageDistance,omitempty" xml:"VariableDeclarationUsageDistance,omitempty"`
	// Checks visibility of class members.
	VisibilityModifier *bool `form:"VisibilityModifier,omitempty" json:"VisibilityModifier,omitempty" xml:"VisibilityModifier,omitempty"`
	// Checks that a token is followed by whitespace, with the exception that it does not check for whitespace after the semicolon of an empty for iterator.
	WhitespaceAfter *bool `form:"WhitespaceAfter,omitempty" json:"WhitespaceAfter,omitempty" xml:"WhitespaceAfter,omitempty"`
	// Checks that a token is surrounded by whitespace.
	WhitespaceAround *bool `form:"WhitespaceAround,omitempty" json:"WhitespaceAround,omitempty" xml:"WhitespaceAround,omitempty"`
	// Outputs a JavaDoc tag as information.
	WriteTag *bool `form:"WriteTag,omitempty" json:"WriteTag,omitempty" xml:"WriteTag,omitempty"`
}

// Description of which Findbugs bugs are checked.
type findbugs struct {
	Name *string `form:"name,omitempty" json:"name,omitempty" xml:"name,omitempty"`
}

// Publicize creates Findbugs from findbugs
func (ut *findbugs) Publicize() *Findbugs {
	var pub Findbugs
	if ut.Name != nil {
		pub.Name = ut.Name
	}
	return &pub
}

// Description of which Findbugs bugs are checked.
type Findbugs struct {
	Name *string `form:"name,omitempty" json:"name,omitempty" xml:"name,omitempty"`
}

// A bug profile
type bugProfile struct {
	Checkstyle *checkstyle `form:"checkstyle,omitempty" json:"checkstyle,omitempty" xml:"checkstyle,omitempty"`
	Findbugs   *findbugs   `form:"findbugs,omitempty" json:"findbugs,omitempty" xml:"findbugs,omitempty"`
	Name       *string     `form:"name,omitempty" json:"name,omitempty" xml:"name,omitempty"`
}

// Publicize creates BugProfile from bugProfile
func (ut *bugProfile) Publicize() *BugProfile {
	var pub BugProfile
	if ut.Checkstyle != nil {
		pub.Checkstyle = ut.Checkstyle.Publicize()
	}
	if ut.Findbugs != nil {
		pub.Findbugs = ut.Findbugs.Publicize()
	}
	if ut.Name != nil {
		pub.Name = ut.Name
	}
	return &pub
}

// A bug profile
type BugProfile struct {
	Checkstyle *Checkstyle `form:"checkstyle,omitempty" json:"checkstyle,omitempty" xml:"checkstyle,omitempty"`
	Findbugs   *Findbugs   `form:"findbugs,omitempty" json:"findbugs,omitempty" xml:"findbugs,omitempty"`
	Name       *string     `form:"name,omitempty" json:"name,omitempty" xml:"name,omitempty"`
}

// payload used to sign up a user
type user struct {
	// User email
	Email       *string `form:"email,omitempty" json:"email,omitempty" xml:"email,omitempty"`
	Name        *string `form:"name,omitempty" json:"name,omitempty" xml:"name,omitempty"`
	Password    *string `form:"password,omitempty" json:"password,omitempty" xml:"password,omitempty"`
	PhoneNumber *string `form:"phone_number,omitempty" json:"phone_number,omitempty" xml:"phone_number,omitempty"`
}

// Validate validates the user type instance.
func (ut *user) Validate() (err error) {
	if ut.Email != nil {
		if err2 := goa.ValidateFormat(goa.FormatEmail, *ut.Email); err2 != nil {
			err = goa.MergeErrors(err, goa.InvalidFormatError(`response.email`, *ut.Email, goa.FormatEmail, err2))
		}
	}
	return
}

// Publicize creates User from user
func (ut *user) Publicize() *User {
	var pub User
	if ut.Email != nil {
		pub.Email = ut.Email
	}
	if ut.Name != nil {
		pub.Name = ut.Name
	}
	if ut.Password != nil {
		pub.Password = ut.Password
	}
	if ut.PhoneNumber != nil {
		pub.PhoneNumber = ut.PhoneNumber
	}
	return &pub
}

// payload used to sign up a user
type User struct {
	// User email
	Email       *string `form:"email,omitempty" json:"email,omitempty" xml:"email,omitempty"`
	Name        *string `form:"name,omitempty" json:"name,omitempty" xml:"name,omitempty"`
	Password    *string `form:"password,omitempty" json:"password,omitempty" xml:"password,omitempty"`
	PhoneNumber *string `form:"phone_number,omitempty" json:"phone_number,omitempty" xml:"phone_number,omitempty"`
}

// Validate validates the User type instance.
func (ut *User) Validate() (err error) {
	if ut.Email != nil {
		if err2 := goa.ValidateFormat(goa.FormatEmail, *ut.Email); err2 != nil {
			err = goa.MergeErrors(err, goa.InvalidFormatError(`response.email`, *ut.Email, goa.FormatEmail, err2))
		}
	}
	return
}
