// Code generated by goagen v1.1.0-dirty, command line:
// $ goagen
// --design=github.com/alligrader/gradebook-api/designs
// --out=$(GOPATH)/src/github.com/alligrader/gradebook-api/src
// --version=v1.1.0-dirty
//
// API "GradebookAPI": Model Helpers
//
// The content of this file is auto-generated, DO NOT MODIFY

package models

import (
	"github.com/alligrader/gradebook-api/src/app"
	"github.com/goadesign/goa"
	"github.com/jinzhu/gorm"
	"golang.org/x/net/context"
	"time"
)

// MediaType Retrieval Functions

// ListUserMt returns an array of view: default.
func (m *UserDB) ListUserMt(ctx context.Context) []*app.UserMt {
	defer goa.MeasureSince([]string{"goa", "db", "userMt", "listuserMt"}, time.Now())

	var native []*User
	var objs []*app.UserMt
	err := m.Db.Scopes().Table(m.TableName()).Find(&native).Error

	if err != nil {
		goa.LogError(ctx, "error listing User", "error", err.Error())
		return objs
	}

	for _, t := range native {
		objs = append(objs, t.UserToUserMt())
	}

	return objs
}

// UserToUserMt loads a User and builds the default view of media type UserMt.
func (m *User) UserToUserMt() *app.UserMt {
	user := &app.UserMt{}
	user.Email = m.Email
	user.ID = &m.ID
	user.Name = m.Name
	user.PhoneNumber = m.PhoneNumber

	return user
}

// OneUserMt loads a User and builds the default view of media type UserMt.
func (m *UserDB) OneUserMt(ctx context.Context, id int) (*app.UserMt, error) {
	defer goa.MeasureSince([]string{"goa", "db", "userMt", "oneuserMt"}, time.Now())

	var native User
	err := m.Db.Scopes().Table(m.TableName()).Where("id = ?", id).Find(&native).Error

	if err != nil && err != gorm.ErrRecordNotFound {
		goa.LogError(ctx, "error getting User", "error", err.Error())
		return nil, err
	}

	view := *native.UserToUserMt()
	return &view, err
}

// MediaType Retrieval Functions

// ListUserMtGithub returns an array of view: github.
func (m *UserDB) ListUserMtGithub(ctx context.Context) []*app.UserMtGithub {
	defer goa.MeasureSince([]string{"goa", "db", "userMt", "listuserMtgithub"}, time.Now())

	var native []*User
	var objs []*app.UserMtGithub
	err := m.Db.Scopes().Table(m.TableName()).Find(&native).Error

	if err != nil {
		goa.LogError(ctx, "error listing User", "error", err.Error())
		return objs
	}

	for _, t := range native {
		objs = append(objs, t.UserToUserMtGithub())
	}

	return objs
}

// UserToUserMtGithub loads a User and builds the github view of media type UserMt.
func (m *User) UserToUserMtGithub() *app.UserMtGithub {
	user := &app.UserMtGithub{}
	user.Email = m.Email
	user.ID = &m.ID
	user.Name = m.Name
	user.PhoneNumber = m.PhoneNumber

	return user
}

// OneUserMtGithub loads a User and builds the github view of media type UserMt.
func (m *UserDB) OneUserMtGithub(ctx context.Context, id int) (*app.UserMtGithub, error) {
	defer goa.MeasureSince([]string{"goa", "db", "userMt", "oneuserMtgithub"}, time.Now())

	var native User
	err := m.Db.Scopes().Table(m.TableName()).Where("id = ?", id).Find(&native).Error

	if err != nil && err != gorm.ErrRecordNotFound {
		goa.LogError(ctx, "error getting User", "error", err.Error())
		return nil, err
	}

	view := *native.UserToUserMtGithub()
	return &view, err
}
