// Code generated by goagen v1.1.0-dirty, command line:
// $ goagen
// --design=github.com/alligrader/gradebook-api/designs
// --out=$(GOPATH)/src/github.com/alligrader/gradebook-api/src
// --version=v1.1.0-dirty
//
// API "GradebookAPI": github_auth Resource Client
//
// The content of this file is auto-generated, DO NOT MODIFY

package client

import (
	"fmt"
	"golang.org/x/net/context"
	"net/http"
	"net/url"
)

// CreateGithubAuthPath computes a request path to the create action of github_auth.
func CreateGithubAuthPath() string {

	return fmt.Sprintf("/api/auth/gh")
}

// Create or login a user with GitHub OAuth
func (c *Client) CreateGithubAuth(ctx context.Context, path string) (*http.Response, error) {
	req, err := c.NewCreateGithubAuthRequest(ctx, path)
	if err != nil {
		return nil, err
	}
	return c.Client.Do(ctx, req)
}

// NewCreateGithubAuthRequest create the request corresponding to the create action endpoint of the github_auth resource.
func (c *Client) NewCreateGithubAuthRequest(ctx context.Context, path string) (*http.Request, error) {
	scheme := c.Scheme
	if scheme == "" {
		scheme = "http"
	}
	u := url.URL{Host: c.Host, Scheme: scheme, Path: path}
	req, err := http.NewRequest("POST", u.String(), nil)
	if err != nil {
		return nil, err
	}
	return req, nil
}
