// Code generated by goagen v1.1.0-dirty, command line:
// $ goagen
// --design=github.com/alligrader/gradebook-api/designs
// --out=$(GOPATH)/src/github.com/alligrader/gradebook-api/src
// --version=v1.1.0-dirty
//
// API "GradebookAPI": GithubToken Resource Client
//
// The content of this file is auto-generated, DO NOT MODIFY

package client

import (
	"fmt"
	"golang.org/x/net/context"
	"net/http"
	"net/url"
)

// ReadGithubTokenPath computes a request path to the read action of GithubToken.
func ReadGithubTokenPath() string {

	return fmt.Sprintf("/api/GHtoken")
}

// Returns the GH token
func (c *Client) ReadGithubToken(ctx context.Context, path string) (*http.Response, error) {
	req, err := c.NewReadGithubTokenRequest(ctx, path)
	if err != nil {
		return nil, err
	}
	return c.Client.Do(ctx, req)
}

// NewReadGithubTokenRequest create the request corresponding to the read action endpoint of the GithubToken resource.
func (c *Client) NewReadGithubTokenRequest(ctx context.Context, path string) (*http.Request, error) {
	scheme := c.Scheme
	if scheme == "" {
		scheme = "http"
	}
	u := url.URL{Host: c.Host, Scheme: scheme, Path: path}
	req, err := http.NewRequest("GET", u.String(), nil)
	if err != nil {
		return nil, err
	}
	return req, nil
}
