package designs

import (
	. "github.com/goadesign/goa/design"
	. "github.com/goadesign/goa/design/apidsl"
)

var _ = API("Gradebook API", func() { // "My API" is the name of the API used in docs
	Title("Gradebook")                // Documentation title
	Description("The next big thing") // Longer documentation description
	Host("localhost:8081")            // Host used by Swagger and clients
	Scheme("http")                    // HTTP scheme used by Swagger and clients
	BasePath("/api")                  // Base path to all API endpoints
	Consumes("application/json")      // Media types supported by the API
	Produces("application/json")      // Media types generated by the API
})
